### ISSUE TITLE
Review comments for your DG

### ISSUE THREAD

**Issue by stephlewyh** [AY2021S2-CS2113-T10-2/tp#80]
1. Better to include table of contents. 
2. Setup section is missing. Other key information about logging, testing and devops are missing as well. 

3. You can omit `v2.0` as it is understood that the code and guide in same commit should correspond.  
<img width="277" alt="Screen Shot 2021-04-04 at 12 37 03 AM" src="https://user-images.githubusercontent.com/2998854/113484992-e1afa500-94dd-11eb-8709-c7259878422c.png">

4. The font is too small, this affects diagram readability.  Resize your diagram and simplify where possible. 
<img width="607" alt="Screen Shot 2021-04-04 at 12 38 46 AM" src="https://user-images.githubusercontent.com/2998854/113485028-1f143280-94de-11eb-9f05-73aa51098911.png">

5.  What are the control classes? What are the entity classes and boundary classes? You could elaborate more or have a diagram that shows what type of classes they are.
<img width="600" alt="Screen Shot 2021-04-04 at 12 41 38 AM" src="https://user-images.githubusercontent.com/2998854/113485095-85995080-94de-11eb-8d8f-5e6eda826b8c.png">

6. This is a better diagram with a right amount of detail. But have class names in Pascal Case and not separate word: `Id: Load Data` -> LoadData. 
<img width="596" alt="Screen Shot 2021-04-04 at 12 43 23 AM" src="https://user-images.githubusercontent.com/2998854/113485138-c3967480-94de-11eb-8657-8f40fb4d59d3.png">

7. Use the same diagramming tool. The font size and color differs across your diagrams, making your document look inconsistent and incohesive. In this sequence diagram the controller and entity symbols are used for the objects, but not in other sequence diagrams.
<img width="489" alt="Screen Shot 2021-04-04 at 12 47 59 AM" src="https://user-images.githubusercontent.com/2998854/113485310-69e27a00-94df-11eb-8612-b69dd094ca44.png">
 
8.  The user stories are good, but you have not stated their priority levels and older stories that led to these v2.0 ones. Which ones were the `must-haves`, `nice-to-have`, `unlikely to have`?  
<img width="257" alt="Screen Shot 2021-04-04 at 12 49 19 AM" src="https://user-images.githubusercontent.com/2998854/113485348-98f8eb80-94df-11eb-99c3-af6c5c2bfef2.png">

9. To complete.. 
<img width="372" alt="Screen Shot 2021-04-04 at 12 53 38 AM" src="https://user-images.githubusercontent.com/2998854/113485466-32c09880-94e0-11eb-858f-795cd3ea16ec.png">
 
Testing other important features?

**Comment by zhangyongzhe20** [comment]
Commits about the fix of feedback7
